### ISSUE TITLE
Error in the worker.py in all branches

### ISSUE THREAD

**Issue by balajig1403** [MysteryDemon/BotClusters#2]
Traceback (most recent call last):
  File "/usr/src/app/worker.py", line 50, in <module>
    bots = load_config("config.json")
  File "/usr/src/app/worker.py", line 29, in load_config
    bots = json.load(jsonfile)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 7 column 13 (char 232)

**Comment by MysteryDemon** [comment]
That was you making mistakes in the config.json file not the code

**Comment by balajig1403** [comment]
i am deploying  every bot individually and it works fine.
Only one bot is running succesfully when I include all my bots in config.json. (same environment variables for both)

That's the main issue  and unable to resolve yet. Could you please assist me with it
